name       : gnome-video-effects
version    : 0.4.3
release    : 3
source     :
    - https://download.gnome.org/sources/gnome-video-effects/0.4/gnome-video-effects-0.4.3.tar.xz : 5a7ee0f5ade4b7d921f1b99f3b97d7d7bb830f2fef0f1daee20a7a1867708219
homepage   : https://git.gnome.org/browse/gnome-video-effects/
license    : GPL-2.0
component  : desktop.gnome.core
summary    : Collection of GStreamer video effects
description: |
    A collection of GStreamer video effects
patterns   :
    - /*
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
