name       : gnome-video-effects
version    : 0.6.0
release    : 5
source     :
    - https://download.gnome.org/sources/gnome-video-effects/0.6/gnome-video-effects-0.6.0.tar.xz : d7aeaeb46b3f5a832fb2e0d90b42bf8c6160202ca52ac9add17afce192e3c8a8
homepage   : https://git.gnome.org/browse/gnome-video-effects/
license    : GPL-2.0
component  : desktop.gnome.core
summary    : Collection of GStreamer video effects
description: |
    A collection of GStreamer video effects
patterns   :
    - /*
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
